/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "STM32F103x8.h"
#include "stm32f103x8_GPIO_driver.h"



void clock_init(){
	//Enable clock of GPIOA
	GPIOA_Clock_Enable();
	//Enable clock of GPIOB
	GPIOB_Clock_Enable();


}
void GPIO_init(){
	//PA1 is input floating

	GPIO_Pinconfig_t* pin_config;
	pin_config->Pin_number=GPIOx_PIN1;
	pin_config->Mode=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, pin_config);

	//PB1 is output push pull mode
	pin_config->Pin_number=GPIOx_PIN1;
	pin_config->Mode=GPIO_MODE_OUTPUT_PP;
	pin_config->Output_speed = GPIO_OUT_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB, pin_config);

	//PA13 is input floating
	pin_config->Pin_number=GPIOx_PIN13;
	pin_config->Mode=GPIO_MODE_INPUT_FLO;
	MCAL_GPIO_INIT(GPIOA, pin_config);


	//PB13 is output push pull mode
	pin_config->Pin_number=GPIOx_PIN13;
	pin_config->Mode=GPIO_MODE_OUTPUT_PP;
	pin_config->Output_speed = GPIO_OUT_SPEED_10M;
	MCAL_GPIO_INIT(GPIOB, pin_config);

}

void wait(){
	for(int i=0; i<2; i++){
		for(int j=0; j<255; j++);
	}
}
int main(void)
{
	clock_init();
	GPIO_init();
	while(1)
	{
		if( MCAL_GPIO_READ_PIN(GPIOA, GPIOx_PIN1) == 0){

			MCAL_GPIO_TogglePin(GPIOB, GPIOx_PIN1);
			while(MCAL_GPIO_READ_PIN(GPIOA, GPIOx_PIN1) == 0);
		}
		if(MCAL_GPIO_READ_PIN(GPIOA, GPIOx_PIN13) == 1){
			MCAL_GPIO_TogglePin(GPIOB, GPIOx_PIN13);
		}
		wait();
	}
}
