/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "lcd.h"
#include "Keypad.h"
#include "stm32f103x8_GPIO_driver.h"
#include "STM32F103x8.h"
#include "stm32f103x8_EXTI_driver.h"

unsigned int IRQ_Flag =0;


void wait_ms(int time){
	for(int i=0; i<time; i++){
		for(int j=0; j<255; j++);
	}
}

void EXTI9_Callback(){
	IRQ_Flag =1;
	LCD_WRITE_STRING("IRQ EXTI9 is happened _|-");
	wait_ms(2000);


}
int main(void)
{
	GPIOA_Clock_Enable();
	GPIOB_Clock_Enable();
	AFIO_Clock_Enable();
	LCD_INIT();
	LCD_clear_screen();
	wait_ms(1000);
	LCD_clear_screen();

	EXTI_Pinconfig_t cfg;
	cfg.EXTI_PIN = EXTI9B9;
	cfg.Trigger_case = EXTI_Trigger_Rising;
	cfg.P_IRQ_Callback = EXTI9_Callback;
	cfg.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_INIT(&cfg);
	IRQ_Flag =1;

    /* Loop forever */
	while(1){
		if(IRQ_Flag){
			LCD_clear_screen();
			IRQ_Flag =0;
		}
	}
}
